[language-server.clangd]
command = "clangd"
args = ["--query-driver=/usr/bin/arm-none-eabi-*"]

[[language]]
name = "c"
language-servers = ["clangd"]

[[language]]
name = "cpp"
language-servers = ["clangd"]
