set shell := ["bash", "-cu"]
cc := "clang"
c-flags := "-Wall -Wextra -Wpedantic -std=c23"
release-flags := "-O3 -march=native"
debug-flags := "-g -O0"
includes := "-I./include"
c-files := "$(fd -e c)"
bin_path := "build/main"

run: build
    ./{{bin_path}}

build: prep
    {{cc}} {{c-flags}} {{debug-flags}} {{includes}} -o {{bin_path}} {{c-files}}

build-leak: prep
    {{cc}} {{c-flags}} -fsanitize=address {{debug-flags}} {{includes}} -o {{bin_path}} {{c-files}}

prep:
    mkdir -p build

release: prep
    {{cc}} {{c-flags}} {{release-flags}} {{includes}} -o {{bin_path}} {{c-files}}

debug: build
    gdb ./{{bin_path}}

clean:
    rm -rf build

relaxed: prep
    {{cc}} -w {{debug-flags}} {{includes}} -o {{bin_path}} {{c-files}}
    ./{{bin_path}}

format:
    clang-format -i {{c-files}}

valgrind: build
    valgrind ./{{bin_path}}
